version: "3.9"
services:
  backend:
    build: .
    container_name: todo
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./core:/app
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=django-insecure-^qy2ug*4^0xx0^b+(^ih-#w$+j_)i!*4ftaeiu0r0a4%^-=(g9
      - DEBUG=True