version: "3.9"
services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  todo:
    build: .
    container_name: todo
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./core:/app
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=django-insecure--dm)rh6=$uqyt8hej!$=nt(-$f%tt339*k4&bl432d)0^7oknh
      - DEBUG=True
      - OPENWEATHER_API_KEY=73c23770764d127fae65f27ffd0971f0
    depends_on:
      - redis
    
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - todo
    

  smtp4dev:
      image: rnwood/smtp4dev:v3
      restart: always
      ports:
        # Change the number before : to the port the web interface should be accessible on
        - '5000:80'
        # Change the number before : to the port the SMTP server should be accessible on
        - '25:25'
        # Change the number before : to the port the IMAP server should be accessible on
        - '143:143'
      volumes:
          - smtp4dev-data:/smtp4dev
      environment:
        # - ServerOptions__Urls=http://*:80
        - ServerOptions__HostName=smtp4dev


volumes:
  smtp4dev-data: