version: "3.9"
services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  todo:
    build: .
    container_name: todo
    command:  gunicorn core.wsgi --bind 0.0.0.0:8080
    volumes:
      - ./core:/app

      - static_volume:/app/static

      - media_volume:/app/media
    expose:
      - "8080"
    environment:
      - SECRET_KEY=django-insecure--dm)rh6=$uqyt8hej!$=nt(-$f%tt339*k4&bl432d)0^7oknh
      - DEBUG=False
    depends_on:
      - redis
    
  nginx:

    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    depends_on:
      - todo
      - redis

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

      - static_volume:/home/app/static

      - media_volume:/home/app/media

volumes:

  static_volume:

  media_volume: