name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Setup Docker-compose
      run: docker-compose -f Docker-compose.yaml up -d

    - name: Run Pytest (Unit Tests)
      run: docker compose exec backend sh -c "pytest ."

    - name: Run Pytest (Unit Tests)
      run: docker compose exec backend sh -c "black ."

    
